name: Download Markdown Images

on:
  push:
    branches:
      - main

jobs:
  download-markdown-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          bun init -y
          bun add @octokit/rest

      - name: Download Images and Update Markdown
        run: bun run process-markdown-images.js

      - name: Push Processed Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email {user.id}+{user.login}@users.noreply.github.com
          git add .
          git commit -m "update image links from external to local"
          git push
