name: Update Website

on:
  workflow_run:
    workflows: ["Download Markdown Images"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Trigger website regeneration
        run: |
          curl -X POST \
            -H "Authorization: ${{ secrets.API_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -f \
            ${{ secrets.API_BASE_URL }}/api/v1/regenerate
